# Generated by Django 5.1.2 on 2024-12-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPost_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
