# Generated by Django 5.1.2 on 2024-12-31 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0002_remove_userprofile_company_name_and_more'),
        ('Category_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=400, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.CharField(max_length=400, null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Category_App.category'),
        ),
    ]
