# Generated by Django 5.1.2 on 2024-12-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0003_userprofile_bio_userprofile_resume_userprofile_skill'),
        ('Category_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skill',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.ManyToManyField(null=True, to='Category_App.category'),
        ),
    ]
